[package]
name = "ontio-wasm-jit"
version = "0.1.0"
authors = ["laizy <aochyi@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cranelift-codegen = "0.46.1"
cranelift-wasm = "0.46.1"
wabt = "0.9.2"
target-lexicon = "0.8.1"
